drivers:
  chrome:
    driver: 'chrome_driver_exe'
    bin: 'chrome_bin'
  firefox:
    driver: 'gecko_driver_exe'
    bin: 'firefox_bin'
grid:
  url: 'http://localhost:4444/wd/hub'
logs:
  config: 'Config/nlog.config'
  folder: 'logs'
apps:
  alza:
    url: 'https://www.alza.cz'
  kariera:
    url: 'https://www.alza.cz/kariera'